# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install    
    - run: npm run prod

    - name: Open Web Client Directory
      working-directory: ./dist
      run: |
        ls -la          
    - name: sftp
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        # username
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PSW }}
        # your sftp server
        host: home34240410.1and1-data.host
        # your sftp server port, default to 22
        port: 22
        # will put all file under this path
        localDir: ./dist/*
        # files will copy to under remote_path
        remoteDir: /test_deploy
